import { ANGULAR } from './posts-angular.constant';
import { ANDROID } from './posts-android.constant';
import { CSS } from './posts-css.constant';
import { DART } from './posts-dart.constant';
import { DEVELOPER } from './posts-developer.constant';
import { ELECTRON } from './posts-electron.contant';
import { FLUTTER } from './posts-flutter.contant';
import { GIT } from './posts-git.constant';
import { HTML } from './posts-html.constant';
import { JAVASCRIPT } from './posts-javascript.constant';
import { DB } from './posts-db.constant';
import { CategoriaPostModel } from '../models/categorias.model';
import { JAVA } from './posts-java.constant';
import { LINUX } from './posts-linux.constant';

export const CATEGORIA: CategoriaPostModel[] = [
    {
        id:1,
        nombre: 'android',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/android.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'android',
        colorFondo: 'bg-Android',
        color: 'c-Android',
        descripcion: '',
        descripcionCorta: '',
        post: ANDROID,
        subcategorias: []
    },
    {
        id:2,
        nombre: 'angular',
        posicion: 'rot-2',
        abertura: '80%',
        rutaIcono: 'assets/img/categorias/angular.png',
        alturaIcono: '80',
        estado:'activo',
        ruta: 'angular',
        colorFondo: 'bg-Angular',
        color: 'c-Angular',
        descripcion: '',
        descripcionCorta: '',
        post: ANGULAR,
        subcategorias: []
    },
    {
        id:3,
        nombre: 'css',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/css.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'css',
        colorFondo: 'bg-Css',
        color: 'c-Css',
        descripcion: '',
        descripcionCorta: '',
        post: CSS,
        subcategorias: []
    },
    {
        id:4,
        nombre: 'dart',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/dart_text_white.png',
        alturaIcono: '40',
        estado:'inactivo',
        ruta: 'dart',
        colorFondo: 'bg-Dart',
        color: 'c-Dart',
        descripcion: '',
        descripcionCorta: '',
        post: DART,
        subcategorias: []
    },
    {
        id:5,
        nombre: 'db',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/sql.png',
        alturaIcono: '55',
        estado:'inactivo',
        ruta: 'db',
        colorFondo: 'bg-Sql',
        color: 'c-Sql',
        descripcion: '',
        descripcionCorta: '',
        post: DB,
        subcategorias: []
    },
    {
        id:6,
        nombre: 'developer',
        posicion: 'rot-2',
        abertura: '80%',
        rutaIcono: 'assets/img/categorias/developer.png',
        alturaIcono: '90',
        estado:'activo',
        ruta: 'developer',
        colorFondo: 'bg-Developer',
        color: 'c-Developer',
        descripcion: '',
        descripcionCorta: '',
        post: DEVELOPER,
        subcategorias: []
    },
    {
        id:7,
        nombre: 'electron',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/electron.png',
        alturaIcono: '90',
        estado:'inactivo',
        ruta: 'electron',
        colorFondo: 'bg-Electron',
        color: 'c-Electron',
        descripcion: '',
        descripcionCorta: '',
        post: ELECTRON,
        subcategorias: []
    },
    {
        id:8,
        nombre: 'flutter',
        posicion: 'rot-1',
        abertura: '',
        rutaIcono: 'assets/img/categorias/flutter_text_white.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'flutter',
        colorFondo: 'bg-Flutter',
        color: 'c-Flutter',
        descripcion: '',
        descripcionCorta: '',
        post: FLUTTER,
        subcategorias: []
    },
    {
        id:9,
        nombre: 'git',
        posicion: 'rot-3',
        abertura: '',
        rutaIcono: 'assets/img/categorias/git-light.png',
        alturaIcono: '60',
        estado:'inactivo',
        ruta: 'git',
        colorFondo: 'bg-Git',
        color: 'c-Git',
        descripcion: '',
        descripcionCorta: '',
        post: GIT,
        subcategorias: []
    },
    {
        id:10,
        nombre: 'html',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/html-white.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'html',
        colorFondo: 'bg-Html',
        color: 'c-Html',
        descripcion: '',
        descripcionCorta: '',
        post: HTML,
        subcategorias: []
    },
    {
        id:11,
        nombre: 'java',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/logo-java.png',
        alturaIcono: '100',
        estado:'inactivo',
        ruta: 'java',
        colorFondo: 'bg-Java',
        color: 'c-Java',
        descripcion: '',
        descripcionCorta: '',
        post: JAVA,
        subcategorias: []
    },
    {
        id:12,
        nombre: 'javascript',
        abertura: '',
        posicion: 'rot-2',
        rutaIcono: 'assets/img/categorias/javascript.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'javascript',
        colorFondo: 'bg-Javascript',
        color: 'c-Javascript',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:13,
        nombre: 'kotlin',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/kotlin.png',
        alturaIcono: '60',
        estado:'inactivo',
        ruta: 'kotlin',
        colorFondo: 'bg-Kotlin',
        color: 'c-Kotlin',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:14,
        nombre: 'kubernetes',
        posicion: 'pos-z',
        abertura: '',
        rutaIcono: 'assets/img/categorias/kubernetes.png',
        alturaIcono: '100',
        estado:'inactivo',
        ruta: 'kubernetes',
        colorFondo: 'bg-Kubernetes',
        color: 'c-Kubernetes',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:13,
        nombre: 'linux',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/linux-white.png',
        alturaIcono: '60',
        estado:'inactivo',
        ruta: 'linux',
        colorFondo: 'bg-Linux',
        color: 'c-Linux',
        descripcion: '',
        descripcionCorta: '',
        post: LINUX,
        subcategorias: []
    },
    {
        id:14,
        nombre: 'net',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/net-framework.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'net',
        colorFondo: 'bg-NetFramework',
        color: 'c-NetFramework',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:15,
        nombre: 'php',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/php.png',
        alturaIcono: '70',
        estado:'inactivo',
        ruta: 'php',
        colorFondo: 'bg-Php',
        color: 'c-Php',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:16,
        nombre: 'react',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/react.png',
        alturaIcono: '100',
        estado:'inactivo',
        ruta: 'react',
        colorFondo: 'bg-React',
        color: ' c-React',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
    {
        id:17,
        nombre: 'wordpress',
        posicion: 'rot-2',
        abertura: '',
        rutaIcono: 'assets/img/categorias/wordpress2.png',
        alturaIcono: '80',
        estado:'inactivo',
        ruta: 'wordpress',
        colorFondo: 'bg-Wordpress',
        color: 'c-Wordpress',
        descripcion: '',
        descripcionCorta: '',
        post: JAVASCRIPT,
        subcategorias: []
    },
]