import { DatosPost, EstilosPost, RefImg } from '@shared/models/categorias.model';

export const ESTILO_ANGULAR: EstilosPost = {
    color: 'c-Angular',
    colorFondo: 'bg-Angular'
}

export const ANGULAR: DatosPost[] = [
    {
        id: 'eb4011f5-81df-4261-b5c5-8f58d2ba88b5',
        nombre: 'Angular',
        descripcion: ['Angular esta en el grupo de los mejores frameworks web, cada 6 meses sin falta entrega una nueva versión y se ha permitido evolucionar.'],
        descripcionCorta: '',
        ruta: 'angular',
        componente: 'AngularComponent',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2021-08-02',
        fechaActualizacion: '2021-08-02',
        imgHorizontal:new RefImg(),
        imgVertical:'',
        imgCuadro:'',
        categoria: 'angular',
        posicion: 'rot-1',
        estado: 'inactivo'
    },
    {
        id: '8618eb718b-655b-49a8-9e6e-f3732922b2df',
        nombre: 'Instalación Angular y recomendados',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-instalacion',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-03-22',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-horizontal.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-3',
        estado: 'activo',
        imgSlider: {
            alt: 'Instalación Angular y recomendados',
            height: '600',
            id: '2',
            ruta: 'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-SLIDER.jpg',
            width: 'auto',
            post: 'ng-instalacion'
        }
    },
    {
        id: 'ca5b7f7a-af2e-47ce-a69e-4ccf6ec2a317',
        nombre: 'Elementos Angular',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-descripcion-elementos',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/elementos.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: '4f414314-8a56-402c-83dc-807b2af9be53',
        nombre: 'Comunicación entre componentes',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-comunicacion-componentes',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/comunicacion_componentes.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-2',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: 'f3d97128-9f99-42e9-b800-cb1425d016cf',
        nombre: 'Arquitecturas propuestas para Angular',
        descripcion: [
            'Teniendo en cuenta que una arquitectura se puede aplicar para todo un proyecto en sus partes de frontend, backend, bases de datos y hasta infraestructura. Esta vez la idea es mostrar la arquitectura aplicando solo al frontend, en este caso a Angular y la aplicacíon a su estructura interna con varios ejemplos dado el caso de interés.',
            'Un esfuerzo máximo se desprende en los inicios por buscar la mejor arquitectura para los proyectos, buscando que todo dure y se quede con las bases del inicio, pero a medida que avanza el desarrollo, van creciendo lo requerimientos, las necesidades y se van definiendo nuevas opciones que no se tuvieron en cuenta al inicio.'
        ],
        descripcionCorta: 'Cual sería el mejor camino a tomar para arrancar un proyecto de angular',
        ruta: 'ng-arquitecturas',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/arquitecturas.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: '7c754f86-a78e-43e3-a6c4-1bad9041c1fa',
        nombre: 'Manejo de rutas en Angular',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-manejo-rutas',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/rutas.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: 'fb64a27a-b6ef-44ea-87e5-ff24d6618bbb',
        nombre: 'Microservicios',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-microservicios',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/microservicios.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-2',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: '3d909134-4cf9-4528-a4e3-1a2781d7e6e1',
        nombre: 'Módulos Angular',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-modulos',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/modulos.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-3',
        estado: 'activo',
        imgSlider: undefined
    },
    {
        id: 'e8512f85-9249-40f0-91d4-1ff9f13db4f0',
        nombre: 'Pruebas unitarias en Angular',
        descripcion: ['Para empezar esta la instalación de angular simplemente, se puede tener en cuenta que trae de especial cada versión, obviamente la última versión nos muestra hasta donde a evolucionado el Framework. También estan los comandos de inicio, de creación y las opciones, que cuando empezamos no los tenemos a la mano.'],
        descripcionCorta: 'Instalación angular. Qué traen las versiones desde la js y todos los comandos del angular que desconocías.',
        ruta: 'ng-pruebas-unitarias',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/unitarias.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-1',
        estado: 'activo',
        imgSlider: undefined
    },
]